### ISSUE TITLE
Constant decimal point

### ISSUE THREAD

**Issue by Craig-Codes** [ElvisMac/calculator#16]
The calculator should always have a decimal point on the screen. 

At the start it should read '0.' Once there is an actual decimal then the decimal will behave correctly.

**Comment by ElvisMac** [comment]
Initialised the display with a decimal in it.  Also updated buildNumber to add the decimal to the display after building the number, then set updateDisplay to check if the user had entered a decimal to account for appending a decimal or not to the end of the number.
