### ISSUE TITLE
Leading zero's

### ISSUE THREAD

**Issue by Craig-Codes** [ElvisMac/calculator#17]
Leading zeros should not be possible. 

As soon as a number is typed after zero, the zero should disappear. 

Currently, 0999999 is possible, it should be 9999999 and the zero is dropped.

**Comment by ElvisMac** [comment]
Fixed the leading zeros issue, seemed to be a two part issue.  Inserted a catch in buildNumber method for both outcomes which accounts for leading zeros, both upon initial number entry and entry after pressing an operand.
