### ISSUE TITLE
square route

### ISSUE THREAD

**Issue by Craig-Codes** [ElvisMac/calculator#39]
If you do a normal square route, all is good e.g. 3, SR = 1.732...

However if you do a sum first, so '6' '/' '2'. '=' 'SR' you get Error and 0 as the result.

This does work fine if you don't press the equals between, so you go straight from '6' '/' '2' 'SR' without the equals before the SR

**Comment by ElvisMac** [comment]
I was passing in this.current in the calculator class, I changed this to display.text and now the square root of the result is working fine.
